name: Hello World
on:
  workflow_dispatch: 
    inputs:
      who-to-greet:
        required: true
        description: 'Who to greet'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Hello World action step
        uses: ./
        id: hello
        with:
          who-to-greet: ${{ inputs.who-to-greet }}