name: Test and Build
on:
  pull_request: 
    branches: 
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Run Tests
        # run: go test ./...
        run: echo "Tests would run here"
      - name: Build Main
        run: CGO_ENABLED=0 GOOS=linux go build -o main main.go
      - name: Test Main
        run: ./main World
      - name: Commit Binary
        run: |
          git add main
          git commit -m 'create `main` binary'
          git push